//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18408
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webServiceCliente.webService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="webserviceProduto", ConfigurationName="webService.wsProdutoSoap")]
    public interface wsProdutoSoap {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento ConsultarProdutoResult no namespace webserviceProduto não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="webserviceProduto/ConsultarProduto", ReplyAction="*")]
        webServiceCliente.webService.ConsultarProdutoResponse ConsultarProduto(webServiceCliente.webService.ConsultarProdutoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="webserviceProduto/ConsultarProduto", ReplyAction="*")]
        System.Threading.Tasks.Task<webServiceCliente.webService.ConsultarProdutoResponse> ConsultarProdutoAsync(webServiceCliente.webService.ConsultarProdutoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarProdutoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarProduto", Namespace="webserviceProduto", Order=0)]
        public webServiceCliente.webService.ConsultarProdutoRequestBody Body;
        
        public ConsultarProdutoRequest() {
        }
        
        public ConsultarProdutoRequest(webServiceCliente.webService.ConsultarProdutoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ConsultarProdutoRequestBody {
        
        public ConsultarProdutoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarProdutoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarProdutoResponse", Namespace="webserviceProduto", Order=0)]
        public webServiceCliente.webService.ConsultarProdutoResponseBody Body;
        
        public ConsultarProdutoResponse() {
        }
        
        public ConsultarProdutoResponse(webServiceCliente.webService.ConsultarProdutoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="webserviceProduto")]
    public partial class ConsultarProdutoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsultarProdutoResult;
        
        public ConsultarProdutoResponseBody() {
        }
        
        public ConsultarProdutoResponseBody(string ConsultarProdutoResult) {
            this.ConsultarProdutoResult = ConsultarProdutoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsProdutoSoapChannel : webServiceCliente.webService.wsProdutoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsProdutoSoapClient : System.ServiceModel.ClientBase<webServiceCliente.webService.wsProdutoSoap>, webServiceCliente.webService.wsProdutoSoap {
        
        public wsProdutoSoapClient() {
        }
        
        public wsProdutoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsProdutoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsProdutoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsProdutoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webServiceCliente.webService.ConsultarProdutoResponse webServiceCliente.webService.wsProdutoSoap.ConsultarProduto(webServiceCliente.webService.ConsultarProdutoRequest request) {
            return base.Channel.ConsultarProduto(request);
        }
        
        public string ConsultarProduto() {
            webServiceCliente.webService.ConsultarProdutoRequest inValue = new webServiceCliente.webService.ConsultarProdutoRequest();
            inValue.Body = new webServiceCliente.webService.ConsultarProdutoRequestBody();
            webServiceCliente.webService.ConsultarProdutoResponse retVal = ((webServiceCliente.webService.wsProdutoSoap)(this)).ConsultarProduto(inValue);
            return retVal.Body.ConsultarProdutoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webServiceCliente.webService.ConsultarProdutoResponse> webServiceCliente.webService.wsProdutoSoap.ConsultarProdutoAsync(webServiceCliente.webService.ConsultarProdutoRequest request) {
            return base.Channel.ConsultarProdutoAsync(request);
        }
        
        public System.Threading.Tasks.Task<webServiceCliente.webService.ConsultarProdutoResponse> ConsultarProdutoAsync() {
            webServiceCliente.webService.ConsultarProdutoRequest inValue = new webServiceCliente.webService.ConsultarProdutoRequest();
            inValue.Body = new webServiceCliente.webService.ConsultarProdutoRequestBody();
            return ((webServiceCliente.webService.wsProdutoSoap)(this)).ConsultarProdutoAsync(inValue);
        }
    }
}
